# Plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"

## plug -- Plugin manager for Kakoune editor
plug "robertmeta/plug.kak" noload

## smarttab -- Automatic handling different styles of indentation and alignment
plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 2
    hook global WinSetOption filetype=(kak|css|python) %{
        set-option window softtabstop 4
    }
} config %{
    hook global WinSetOption filetype=(.*) expandtab
}
## prelude -- Prelude of shell blocks for Kakoune

plug "alexherbo2/prelude.kak"

## auto-pairs -- Auto-paired characters for Kakoune
plug "alexherbo2/auto-pairs.kak" config %{
    require-module auto-pairs

    auto-pairs-enable
}

## surround -- Surround pairs as-you-type for Kakoune
plug "alexherbo2/surround.kak" config %{
    require-module surround
}

## move-line -- Kakoune plugin to move lines without `xdp`
plug "alexherbo2/move-line.kak" config %{
    require-module move-line

    map global normal "'" ': move-line-below<ret>'
    map global normal "<a-'>" ': move-line-above<ret>'
}

plug "andreyorst/powerline.kak" config %{
    # %sh{
    #     if [ $TERM = "linux" ]; then
    #         echo nop
    #     else
    #         echo powerline-start
    #     fi
    # }
}

# kak-lsp
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
} config %{
    set global lsp_diagnostic_line_error_sign '║'
    set global lsp_diagnostic_line_warning_sign '┊'
}

# Snippets
plug "alexherbo2/snippets.kak" config %{
    set-option global snippets_scope global
    map global user -docstring 'Edit snippets' / ': snippets-edit<ret>'
    map global insert <ret> '<a-;>: snippets-enter auto-pairs-insert-new-line<ret>'
    hook global BufCreate '.+/\.?config/snippets/.+' %{
        set-option buffer indentwidth 0
    }
}

# phantom.kak (idk what it does)
plug "alexherbo2/phantom.kak"

# terminal-mode.kak
plug "alexherbo2/terminal-mode.kak" config %{
    map global normal -docstring 'Terminal' <c-w> ': enter-user-mode terminal<ret>'
}

# connect.kak
plug "alexherbo2/connect.kak"

# batch.kak
plug "alexherbo2/batch.kak"

# explore.kak
plug "alexherbo2/explore.kak"

# Indent Width
set-option global indentwidth 2
hook global WinSetOption filetype=(kak|css|python) %{
    set-option window indentwidth 4
}

# Highlighters

# hook global ModeChange push:normal:insert %{
#     add-highlighter -override window/line-numbers number-lines -hlcursor
# }

# hook global ModeChange pop:insert:normal %{
#     add-highlighter -override window/line-numbers number-lines -hlcursor -relative
# }

# add-highlighter global/line-numbers number-lines -hlcursor -relative
add-highlighter global/line-numbers number-lines -hlcursor
add-highlighter global/line-wrap wrap

# Colorschemes
plug "TeddyDD/kakoune-selenized" theme
plug "Delapouite/kakoune-colors" theme
plug "evanrelf/primer.kak" theme
plug "caksoylar/kakoune-snow" theme
plug "rubberydub/nord-kakoune" theme
plug "caksoylar/kakoune-mysticaltutor" theme config %{
    %sh{
        if [ $TERM = "linux" ]; then
            echo nop
        else
            echo colorscheme
        fi
    } mysticaltutor
}

plug "jordan-yee/kakoune-mysticaltutor-powerline" defer powerline %{
    powerline-theme mysticaltutor
}

# Javascript & JSX format
hook global WinSetOption filetype=javascript %{
    set-option buffer formatcmd 'prettier --parser babel'
}

# HTML format
hook global WinSetOption filetype=html %{
    set-option buffer formatcmd 'prettier --parser html'
}
