---
theme:
  active: Green
  banner: White
  error_border: Red
  error_text: White
  hint: Red
  hovered: Red
  inactive: White
  playbar_background: Black
  playbar_progress: Red
  playbar_text: White
  selected: Green
  text: White
...
